### ISSUE TITLE
@nx-plus/docusaurus Fails to serve/build with latest version of nx

### ISSUE THREAD

**Issue by paustint** [ZachJW34/nx-plus#197]
I suspect this has to do with webpack in some capacity.

1. Start new nx project, add a react app
2. install plugin
3. generate app from plugin
4. attempt to server or build plugin

Sample codebase with issue: https://github.com/paustint/nx-12-test

Seems the same as this: https://github.com/facebook/docusaurus/issues/4709

run `nx serve docs` to reproduce

NOTE: This is a stock nx project OOB, nothing here at all, no customizations of anything - just a few apps and libraries I was using to compare changes in nx 11 vs nx 12 for upgrade purposes.

## Current Behavior

```
/Users/aturner/dev/node/nx-12-test-project/node_modules/webpack/lib/ProgressPlugin.js:242
                                        compilation.hooks[name].intercept({
                                                                ^

TypeError: Cannot read property 'intercept' of undefined
    at /Users/aturner/dev/node/nx-12-test-project/node_modules/webpack/lib/ProgressPlugin.js:242:30
    at Array.forEach (<anonymous>)
    at /Users/aturner/dev/node/nx-12-test-project/node_modules/webpack/lib/ProgressPlugin.js:239:24
    at Hook.eval [as call] (eval at create (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:102:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:1044:26)
    at /Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:1088:29
    at Hook.eval [as callAsync] (eval at create (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:1083:28)
    at /Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Watching.js:200:19
    at Hook.eval [as callAsync] (eval at create (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/tapable/lib/Hook.js:18:14)
    at run (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Watching.js:154:33)
    at /Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Watching.js:149:6
    at Compiler.readRecords (/Users/aturner/dev/node/nx-12-test-project/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:920:11)
```

## Expected Behavior

Serve and build should work

## Steps to Reproduce

https://github.com/paustint/nx-12-test

checkout, serve or build

### Failure Logs

see above

### Environment

Plugin name and version: 
` "@nx-plus/docusaurus": "^12.2.0",`

```
>  NX  Report complete - copy this into the issue template

  Node : 15.14.0
  OS   : darwin x64
  npm  : 7.7.6
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

![image](https://user-images.githubusercontent.com/5461649/134263367-d5b2d80b-98a5-4aab-b9dd-709f0949fc40.png)

**Comment by paustint** [comment]
Upgrading to webpack 5 https://nx.dev/l/a/guides/webpack-5 solved this issue.
