### ISSUE TITLE
docusaurus.config.js not found

### ISSUE THREAD

**Issue by adrian-ub** [ZachJW34/nx-plus#21]
run the following command `nx serve docs`

```
// angular.json

"docs": {
    "projectType": "application",
    "root": "apps/docs",
    "sourceRoot": "apps/docs/src",
    "architect": {
      "build": {
        "builder": "@nx-plus/docusaurus:build-docusaurus",
        "options": {
          "outputPath": "dist/docusaurus/docs"
        }
      },
      "serve": {
        "builder": "@nx-plus/docusaurus:docusaurus",
        "options": {
          "port": 3000
        }
      }
    }
  }
},

```

```
[error] Error: docusaurus.config.js not found
    at Object.loadConfig (G:\Aplicacion\app\node_modules\@docusaurus\core\lib\server\config.js:43:15)
    at loadContext (G:\Aplicacion\app\node_modules\@docusaurus\core\lib\server\index.js:24:33)
    at Object.load (G:\Aplicacion\app\node_modules\@docusaurus\core\lib\server\index.js:52:21)
    at Object.start (G:\Aplicacion\app\node_modules\@docusaurus\core\lib\commands\start.js:45:34)
    at Observable._subscribe (G:\Aplicacion\app\node_modules\@nx-plus\docusaurus\src\builders\docusaurus\builder.js:10:15)
    at Observable._trySubscribe (G:\Aplicacion\app\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (G:\Aplicacion\app\node_modules\rxjs\internal\Observable.js:30:22)
    at Object.subscribeToResult (G:\Aplicacion\app\node_modules\rxjs\internal\util\subscribeToResult.js:12:23)
    at SwitchMapSubscriber._innerSub (G:\Aplicacion\app\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (G:\Aplicacion\app\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (G:\Aplicacion\app\node_modules\rxjs\internal\Subscriber.js:66:18)
    at G:\Aplicacion\app\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
```

**Comment by ZachJW34** [comment]
I can't reproduce this error inside a fresh nx workspace (with and without `ng`). Can you provide more details such as your dependency versions and any other changes you made to what the schematic generated for you?

**Comment by amitnn** [comment]
Thank you for creating this plugin. I am able to recreate this problem. steps to reproduce.

1. npx create-nx-workspace --> empty with nx cli
2. npm install --save-dev @nx-plus/docusaurus
3. npx nx g @nx-plus/docusaurus:app my-docs-app
4. npx nx run my-docs-app:build-docusaurus

Starting the development server...
docusaurus.config.js not found

I use the Nx console with the same results.

"dependencies": {
    "@docusaurus/core": "^2.0.0-alpha.50",
    "@docusaurus/preset-classic": "^2.0.0-alpha.50",
    "classnames": "^2.2.6",
    "react": "^16.8.4",
    "react-dom": "^16.8.4"
  },
  "devDependencies": {
    "@nrwl/workspace": "9.2.4",
    "@nx-plus/docusaurus": "0.0.3",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "prettier": "1.19.1",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~3.8.3"
  }

Any help is appreciated. Thank you

**Comment by ZachJW34** [comment]
Release [v0.0.4](https://github.com/ZachJW34/nx-plus/releases/tag/v0.0.4) includes the fix for this issue. Check it out!
