### ISSUE TITLE
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in workspace.json

### ISSUE THREAD

**Issue by mklueh** [ZachJW34/nx-plus#210]
Hello, I'm trying to use this plugin on a freshly created workspace, but something is not working expectedly.

```
user@MYPC:~/workspace/nx-demo$ nx g @nx-plus/vue:lib my-vue-lib
✔ Which version of Vue.js would you like to use? · 2
✔ Use Babel alongside TypeScript? (y/N) · true

[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
TypeError: Cannot set properties of undefined (setting 'my-vue-lib')
    at /home/user/workspace/nx-demo/node_modules/@nrwl/workspace/src/utils/ast-utils.js:369:36
    at /home/user/workspace/nx-demo/node_modules/@nrwl/workspace/src/utils/ast-utils.js:359:58
    at MergeMapSubscriber.project (/home/user/workspace/nx-demo/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/home/user/workspace/nx-demo/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/user/workspace/nx-demo/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/user/workspace/nx-demo/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/user/workspace/nx-demo/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/user/workspace/nx-demo/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/user/workspace/nx-demo/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/user/workspace/nx-demo/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
Cannot set properties of undefined (setting 'my-vue-lib')

```
package.json dependencies
```
"devDependencies": {
    "@angular-devkit/build-angular": "^13.1.2",
    "@nrwl/angular": "^13.4.1",
    "@nrwl/cli": "13.4.1",
    "@nrwl/cypress": "^12.6.0",
    "@nrwl/eslint-plugin-nx": "13.4.1",
    "@nrwl/jest": "^12.6.0",
    "@nrwl/js": "13.4.1",
    "@nrwl/linter": "^12.6.0",
    "@nrwl/react": "^13.4.1",
    "@nrwl/tao": "13.4.1",
    "@nrwl/web": "13.4.1",
    "@nrwl/workspace": "^12.6.0",
    "@nx-plus/nuxt": "^12.2.0",
    "@nx-plus/vue": "^12.2.0",
    "@testing-library/react": "12.1.2",
    "@testing-library/react-hooks": "7.0.2",
    "@types/jest": "27.0.2",
    "@types/node": "14.14.33",
    "@types/react": "17.0.30",
    "@types/react-dom": "17.0.9",
    "@types/react-router-dom": "5.3.1",
    "@typescript-eslint/eslint-plugin": "~5.3.0",
    "@typescript-eslint/parser": "~5.3.0",
    "babel-jest": "27.2.3",
    "cypress": "^9.1.0",
    "eslint": "8.2.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.25.2",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.26.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "27.2.3",
    "prettier": "^2.3.1",
    "react-test-renderer": "17.0.2",
    "ts-jest": "27.0.5",
    "typescript": "~4.4.3"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-router-dom": "5.3.0",
    "regenerator-runtime": "0.13.7",
    "tslib": "^2.0.0"
  }

```

workspace.json
```
{
  "version": 2,
  "projects": {
  }
}

```

Why are there any angular dependencies being called and what is wrong with my workspace.json ?

**Comment by mklueh** [comment]
This was caused by using the wrong nx versions, see https://github.com/ZachJW34/nx-plus/issues/211
