### ISSUE TITLE
NX 13 support

### ISSUE THREAD

**Issue by JonathanWilbur** [ZachJW34/nx-plus#222]
I force-installed this app in an NX 13 monorepo and I got this error in the console:

```
TypeError: workspace_1.toFileName is not a function
    at normalizeOptions (/home/jonathan/repos/directory/node_modules/@nx-plus/docusaurus/src/schematics/app/schematic.js:12:30)
    at /home/jonathan/repos/directory/node_modules/@nx-plus/docusaurus/src/schematics/app/schematic.js:74:35
    at MergeMapSubscriber.project (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/home/jonathan/repos/directory/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:37:23)
workspace_1.toFileName is not a function
The terminal process "bash '-c', 'npx nx generate @nx-plus/docusaurus:app --name=docs --no-interactive --dry-run'" terminated with exit code: 1.
```

This might not be the only issue, but maybe it would help somebody fix this.

**Comment by JonathanWilbur** [comment]
Also, I used `console.log()` to inspect what this object looks like:

```
{
  readTsConfig: [Getter],
  ProjectType: [Getter],
  projectRootDir: [Getter],
  renameSync: [Getter],
  updateJsonFile: [Getter],
  copyFile: [Getter],
  createDirectory: [Getter],
  resolveUserExistingPrettierConfig: [Getter],
  output: [Getter],
  commandsObject: [Getter],
  supportedNxCommands: [Getter],
  readWorkspaceJson: [Getter],
  readNxJson: [Getter],
  readWorkspaceConfig: [Getter],
  readPackageJson: [Getter],
  readJsonInTree: [Getter],
  updateJsonInTree: [Getter],
  updateWorkspaceInTree: [Getter],
  insert: [Getter],
  replaceNodeValue: [Getter],
  addDepsToPackageJson: [Getter],
  addMethod: [Getter],
  addIncludeToTsConfig: [Getter],
  addGlobal: [Getter],
  getProjectConfig: [Getter],
  addParameterToConstructor: [Getter],
  createOrUpdate: [Getter],
  findNodes: [Getter],
  updatePackageJsonDependencies: [Getter],
  readWorkspace: [Getter],
  renameSyncInTree: [Getter],
  renameDirSyncInTree: [Getter],
  updateNxJsonInTree: [Getter],
  addProjectToNxJsonInTree: [Getter],
  readNxJsonInTree: [Getter],
  InsertChange: [Getter],
  ReplaceChange: [Getter],
  RemoveChange: [Getter],
  getNpmScope: [Getter],
  getWorkspacePath: [Getter],
  replaceAppNameWithPath: [Getter],
  editTarget: [Getter],
  parseTarget: [Getter],
  serializeTarget: [Getter],
  unparse: [Getter],
  getWorkspace: [Getter],
  updateWorkspace: [Getter],
  updateBuilderConfig: [Getter],
  addUpdateTask: [Getter],
  addLintFiles: [Getter],
  generateProjectLint: [Getter],
  addInstallTask: [Getter],
  formatFiles: [Getter],
  deleteFile: [Getter],
  updateKarmaConf: [Getter],
  visitNotIgnoredFiles: [Getter],
  setDefaultCollection: [Getter],
  renamePackageImports: [Getter],
  renameNpmPackages: [Getter],
  checkAndCleanWithSemver: [Getter],
  updatePackagesInPackageJson: [Getter],
  libraryGenerator: [Getter],
  moveGenerator: [Getter],
  removeGenerator: [Getter],
  runCommandsGenerator: [Getter],
  convertToNxProjectGenerator: [Getter],
  convertToNxProjectSchematic: [Getter],
  stringUtils: {
    decamelize: [Function: decamelize],
    dasherize: [Function: dasherize],
    camelize: [Function: camelize],
    classify: [Function: classify],
    underscore: [Function: underscore],
    capitalize: [Function: capitalize],
    group: [Function: group],
    featurePath: [Function: featurePath]
  },
  addPackageWithInit: [Getter]
}
```

**Comment by MisterBE2** [comment]
I have te same issue.

**Comment by keadex** [comment]
Same issues here.

In Nx 13, `toFileName()` and `offsetFromRoot()` are exported by the the `@nrwl/devkit` package.

So, I've tried the following quick & dirty patch of the `node_modules\@nx-plus\docusaurus\src\schematics\app\schematic.js` file:

- Added the `const devkit_1 = require('@nrwl/devkit');` at the bottom of the file
- Changed the `toFileName()` usage (e.g. `workspace_1.toFileName(options.name)`) in something like `devkit_1.names(options.name).fileName`
- Changed the `offsetFromRoot()` usage (e.g. `workspace_1.offsetFromRoot(options.projectRoot)`) in something like `devkit_1.offsetFromRoot(options.projectRoot)`

Now I'm able to create a docusaurus app and to serve that. But it's probable that there could be other regressions introduced by Nx 13.

**Comment by fxck** [comment]
Any plans to release nx 13 compatible version @ZachJW34?

**Comment by fxck** [comment]
I tried forking the update-all branch, it did manage to generate the library, but not having much luck building it

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1303561/157261405-3c6a8fa5-969a-4084-a727-5566569d6a5e.png">

I can't get Nx to be more verbose..

**Comment by ZachJW34** [comment]
I've just published v13 for all packages. Try them out and let me know how they work!

**Comment by JonathanWilbur** [comment]
This works now @ZachJW34 . Thank you so much for fixing this!
