### ISSUE TITLE
This does not work past any step 1. Broken on initialize.

### ISSUE THREAD

**Issue by prodkt** [ZachJW34/nx-plus#231]
## Current Behavior
nx build

> nx run vue-app:build

⠙  Building for development...TypeError: Cannot read properties of undefined (reading 'NormalModule')
    at VueLoaderPlugin.apply (/Users/xx/Prodkt/MOYO-Design-System/core/moyo-design-system/node_modules/vue-loader-v16/dist/pluginWebpack5.js:44:47)
    at webpack (/Users/xx/Prodkt/MOYO-Design-System/core/moyo-design-system/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
    at /Users/xx/Prodkt/MOYO-Design-System/core/moyo-design-system/node_modules/@vue/cli-service/lib/commands/build/index.js:200:5
    at new Promise (<anonymous>)
    at build (/Users/xx/Prodkt/MOYO-Design-System/core/moyo-design-system/node_modules/@vue/cli-service/lib/commands/build/index.js:199:10)
    at async /Users/xx/Prodkt/MOYO-Design-System/core/moyo-design-system/node_modules/@vue/cli-service/lib/commands/build/index.js:89:7

## Expected Behavior
For it to work.

## Steps to Reproduce
Follow your steps of this repo

### Environment

Plugin name and version: 

   Node : 17.8.0
   OS   : darwin arm64
   npm  : 8.6.0
   
   nx : 13.9.5
   @nrwl/angular : 13.9.6
   @nrwl/cypress : 13.9.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.6
   @nrwl/linter : 13.9.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.6
   @nrwl/web : 13.9.5
   @nrwl/workspace : 13.9.5
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @nx-plus/vue: 13.0.0
         @nxext/stencil: 13.2.3
         @nxext/svelte: 13.3.0

**Comment by ZachJW34** [comment]
Can you create a reproduction? Looks like it resolving Webpack 5 which vue-cli@4 doesn't support

**Comment by konrad-synergy** [comment]
> Can you create a reproduction? Looks like it resolving Webpack 5 which vue-cli@4 doesn't support

downgrading to webpack 4 solves it, although I don't know if that wont bite me later on...

**Comment by Xaz16** [comment]
I have the same issue, but I have others project in my nx workspace (angular and react apps) and I can't just downgrade webpack to 4. But as I see in vue-cli they have 5th major version with support of 5th webpack. @ZachJW34 is it possible to update dependcies inside this project? 
https://github.com/vuejs/vue-cli/releases?page=2
